export const CREATE_JOB_ERROR = 'CREATE_JOB_ERROR';
export const CREATE_JOB_SUCCESS = 'CREATE_JOB_SUCCESS';

export const FILTER_JOBS = 'FILTER_JOBS';
export const LOAD_JOBS_SUCCESS = 'LOAD_JOBS_SUCCESS';
export const UNLOAD_JOBS_SUCCESS = 'UNLOAD_JOBS_SUCCESS';
